"""Compliance Wizard templates — pre-built search suites for common regulations."""

COMPLIANCE_TEMPLATES = {
    "Financial Services (SOX/BSA/AML)": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_ssn", "desc": "No Social Security numbers in any document",
         "search_text": r"\d{3}-\d{2}-\d{4}", "regex": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in active folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "has_date", "desc": "Every file contains a date",
         "search_text": r"\d{2}/\d{2}/\d{4}", "regex": True, "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "sox_reference", "desc": "At least one document references SOX compliance",
         "search_text": "SOX",
         "operator": ">=", "threshold": 1},
        {"name": "bsa_aml_reference", "desc": "Anti-money laundering documentation exists",
         "search_text": "BSA OR AML", "expression": True,
         "operator": ">=", "threshold": 1},
        {"name": "large_transactions", "desc": "Transactions in reportable range documented",
         "search_text": "transaction", "range_filters": "amount:10000..50000",
         "operator": ">=", "threshold": 1},
        {"name": "account_numbers", "desc": "Account numbers are traceable",
         "search_text": r"ACCT-\d+", "regex": True,
         "operator": ">=", "threshold": 1},
    ],

    "Healthcare (HIPAA)": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_ssn", "desc": "No SSNs exposed in documents (HIPAA)",
         "search_text": r"\d{3}-\d{2}-\d{4}", "regex": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No unapproved drafts",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "hipaa_reference", "desc": "HIPAA compliance documented",
         "search_text": "HIPAA",
         "operator": ">=", "threshold": 1},
        {"name": "diagnosis_codes", "desc": "ICD-10 diagnosis codes present in clinical docs",
         "search_text": r"[A-Z]\d{2}\.\d", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "billing_amounts", "desc": "Billing amounts documented",
         "search_text": "billing", "range_filters": "amount:100..50000",
         "operator": ">=", "threshold": 1},
        {"name": "mrn_in_transfer", "desc": "Medical record numbers accompany transfers",
         "search_text": "MRN AND transfer", "expression": True,
         "operator": ">=", "threshold": 1},
        {"name": "patient_consent", "desc": "Consent documentation exists",
         "search_text": "consent",
         "operator": ">=", "threshold": 1},
    ],

    "Legal Document Review": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "has_indemnification", "desc": "Every agreement has indemnification clause",
         "search_text": "indemnif", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "has_effective_date", "desc": "Every agreement has an effective date",
         "search_text": "Effective Date", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in active folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "no_privileged", "desc": "No privileged documents in production set",
         "search_text": "PRIVILEGED",
         "operator": "==", "threshold": 0},
        {"name": "settlement_amounts", "desc": "Settlement amounts documented",
         "search_text": "settlement", "range_filters": "amount:1000..1000000",
         "operator": ">=", "threshold": 1},
        {"name": "case_numbers", "desc": "Case numbers present and traceable",
         "search_text": r"\d{4}-CV-\d+", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "nda_exists", "desc": "Non-disclosure agreements on file",
         "search_text": "non-disclosure OR nondisclosure OR NDA", "expression": True,
         "operator": ">=", "threshold": 1},
    ],

    "Government Records": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in official folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "no_classified", "desc": "No classified markings in unclassified folder",
         "search_text": "CONFIDENTIAL OR CLASSIFIED OR SECRET", "expression": True,
         "operator": "==", "threshold": 0},
        {"name": "has_date", "desc": "Every document contains a date",
         "search_text": r"\d{2}/\d{2}/\d{4}", "regex": True, "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "procurement_authorized", "desc": "Procurement actions have authorization",
         "search_text": "procurement AND authorized", "expression": True,
         "operator": ">=", "threshold": 1},
        {"name": "budget_amounts", "desc": "Budget allocations documented",
         "search_text": "budget", "range_filters": "amount:10000..50000000",
         "operator": ">=", "threshold": 1},
        {"name": "purchase_orders", "desc": "Purchase orders traceable",
         "search_text": r"PO-\d{4}", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "foia_compliance", "desc": "FOIA documentation exists",
         "search_text": "FOIA",
         "operator": ">=", "threshold": 1},
    ],

    "Manufacturing (ISO 9001)": [
        {"name": "has_signature", "desc": "Every file has quality sign-off",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No unapproved drafts in production folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "no_expired_certs", "desc": "No expired certifications in active files",
         "search_text": "expired",
         "operator": "==", "threshold": 0},
        {"name": "iso_reference", "desc": "ISO 9001 compliance documented",
         "search_text": "ISO 9001",
         "operator": ">=", "threshold": 1},
        {"name": "lot_numbers", "desc": "Lot/batch numbers traceable",
         "search_text": r"LOT-\d{4}-\d+", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "part_numbers", "desc": "Part numbers documented",
         "search_text": r"[A-Z]{3}-\d{4}", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "nonconformance_closed", "desc": "Nonconformances have corrective actions",
         "search_text": "nonconformance AND corrective", "expression": True,
         "operator": ">=", "threshold": 1},
        {"name": "calibration_current", "desc": "Calibration records exist",
         "search_text": "calibration",
         "operator": ">=", "threshold": 1},
    ],

    "Education (FERPA)": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_ssn", "desc": "No student SSNs exposed (FERPA violation)",
         "search_text": r"\d{3}-\d{2}-\d{4}", "regex": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in official folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "ferpa_reference", "desc": "FERPA compliance documented",
         "search_text": "FERPA",
         "operator": ">=", "threshold": 1},
        {"name": "grant_amounts", "desc": "Grant amounts documented",
         "search_text": "grant", "range_filters": "amount:1000..10000000",
         "operator": ">=", "threshold": 1},
        {"name": "accreditation_docs", "desc": "Accreditation documentation exists",
         "search_text": "accreditation",
         "operator": ">=", "threshold": 1},
        {"name": "student_ids", "desc": "Student IDs (not SSNs) used for identification",
         "search_text": "Student ID",
         "operator": ">=", "threshold": 1},
        {"name": "financial_aid", "desc": "Financial aid records exist",
         "search_text": "financial aid OR scholarship", "expression": True,
         "operator": ">=", "threshold": 1},
    ],

    "Real Estate Closing": [
        {"name": "has_signature", "desc": "Every file has a signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in closing folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "has_date", "desc": "Every document contains a date",
         "search_text": r"\d{2}/\d{2}/\d{4}", "regex": True, "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "disclosure_present", "desc": "Required disclosures on file",
         "search_text": "disclosure",
         "operator": ">=", "threshold": 1},
        {"name": "property_values", "desc": "Property values documented",
         "search_text": "property", "range_filters": "amount:100000..1000000",
         "operator": ">=", "threshold": 1},
        {"name": "square_footage", "desc": "Square footage documented",
         "search_text": r"\d[\d,]+ sq ft", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "title_search", "desc": "Title search documentation exists",
         "search_text": "title",
         "operator": ">=", "threshold": 1},
        {"name": "inspection_report", "desc": "Property inspection on file",
         "search_text": "inspection",
         "operator": ">=", "threshold": 1},
    ],

    "Insurance Compliance": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in active folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "no_lapsed_policies", "desc": "No lapsed policies in active folder",
         "search_text": "lapsed OR expired", "expression": True,
         "operator": "==", "threshold": 0},
        {"name": "state_mandated_language", "desc": "Required state-mandated language present",
         "search_text": "state-mandated",
         "operator": ">=", "threshold": 1},
        {"name": "premium_amounts", "desc": "Premium amounts documented",
         "search_text": "premium", "range_filters": "amount:100..10000",
         "operator": ">=", "threshold": 1},
        {"name": "policy_numbers", "desc": "Policy numbers traceable",
         "search_text": r"POL-\d{4}-\d+", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "claim_numbers", "desc": "Claims have reference numbers",
         "search_text": r"CLM-\d{4}-\d+", "regex": True,
         "operator": ">=", "threshold": 1},
        {"name": "underwriting_review", "desc": "Underwriting documentation exists",
         "search_text": "underwriting",
         "operator": ">=", "threshold": 1},
    ],

    "HR Compliance": [
        {"name": "has_signature", "desc": "Every file has an authorized signature",
         "search_text": "Authorized Signature", "inverse": True,
         "operator": "==", "threshold": 0},
        {"name": "no_ssn", "desc": "No SSNs on shared drives",
         "search_text": r"\d{3}-\d{2}-\d{4}", "regex": True,
         "operator": "==", "threshold": 0},
        {"name": "no_draft", "desc": "No draft documents in official folder",
         "search_text": "DRAFT",
         "operator": "==", "threshold": 0},
        {"name": "offer_letters", "desc": "Offer letter documentation exists",
         "search_text": "offer",
         "operator": ">=", "threshold": 1},
        {"name": "i9_verification", "desc": "I-9 employment verification records exist",
         "search_text": "I-9",
         "operator": ">=", "threshold": 1},
        {"name": "salary_amounts", "desc": "Salary/compensation documented",
         "search_text": "salary", "range_filters": "amount:50000..200000",
         "operator": ">=", "threshold": 1},
        {"name": "eeoc_compliance", "desc": "Equal employment documentation exists",
         "search_text": "EEOC OR EEO-1", "expression": True,
         "operator": ">=", "threshold": 1},
        {"name": "flsa_reference", "desc": "Fair Labor Standards Act compliance documented",
         "search_text": "FLSA",
         "operator": ">=", "threshold": 1},
    ],
}

COMPLIANCE_CATEGORY_ORDER = [
    "Financial Services (SOX/BSA/AML)",
    "Healthcare (HIPAA)",
    "Legal Document Review",
    "Government Records",
    "Manufacturing (ISO 9001)",
    "Education (FERPA)",
    "Real Estate Closing",
    "Insurance Compliance",
    "HR Compliance",
]
