"""Search Wizard pattern definitions for profession-specific regex presets."""

WIZARD_PATTERNS = {
    "Common / General": [
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Date (YYYY-MM-DD)", r"\d{4}-\d{1,2}-\d{1,2}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Percentage", r"\d+\.?\d*\s*%"),
        ("Phone Number", r"\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}"),
        ("Email Address", r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"),
        ("6-digit Number", r"\d{6}"),
        ("SSN (XXX-XX-XXXX)", r"\d{3}-\d{2}-\d{4}"),
    ],
    "Business / Finance": [
        ("Invoice Number", r"INV[-\s]?\d{4,}"),
        ("Purchase Order", r"PO[-\s]?\d{4,}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Tax ID / EIN", r"\d{2}-\d{7}"),
        ("Account Number", r"[Aa]cct?\.?\s*#?\s*\d{4,}"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
    ],
    "Legal": [
        ("Case Number", r"\d{2}-[A-Z]{2}-\d{4,}"),
        ("Statute Reference", r"§\s*\d+"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Bates Number", r"[A-Z]{2,}\d{6,}"),
        ("Court Docket", r"[Nn]o\.\s*\d{2}-\d{4,}"),
    ],
    "Medical / Healthcare": [
        ("ICD-10 Code", r"[A-Z]\d{2}\.?\d{0,2}"),
        ("CPT Code", r"\d{5}"),
        ("NPI Number", r"\d{10}"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Patient ID", r"[Pp]atient\s*#?\s*\d{4,}"),
    ],
    "Engineering / Technical": [
        ("Part Number", r"[A-Z]{2,3}-\d{4,}"),
        ("Revision Number", r"[Rr]ev\.?\s*[A-Z0-9]+"),
        ("Measurement", r"\d+\.?\d*\s*(mm|cm|m|in|ft|kg|lb|psi|MPa)"),
        ("Serial Number", r"S/?N[: ]?\s*[A-Z0-9-]{4,}"),
        ("Tolerance", r"[±+\-]\s*\d+\.?\d*"),
        ("Drawing Number", r"DWG[-\s]?\d{4,}"),
    ],
    "Real Estate": [
        ("Parcel / APN", r"\d{3}-\d{3}-\d{3}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Square Footage", r"[\d,]+\s*sq\.?\s*ft"),
        ("Lot/Block", r"[Ll]ot\s+\d+"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("MLS Number", r"MLS[#\s]?\d{5,}"),
    ],
    "HR / Admin": [
        ("SSN (XXX-XX-XXXX)", r"\d{3}-\d{2}-\d{4}"),
        ("Employee ID", r"[Ee]mp\.?\s*#?\s*\d{4,}"),
        ("Phone Number", r"\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}"),
        ("Email Address", r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
    ],
    "Compliance / Audit": [
        ("SSN (XXX-XX-XXXX)", r"\d{3}-\d{2}-\d{4}"),
        ("Tax ID / EIN", r"\d{2}-\d{7}"),
        ("Employee ID", r"[Ee]mp\.?\s*#?\s*\d{4,}"),
        ("Dollar Amount", r"\$[\d,]+\.?\d*"),
        ("Date (MM/DD/YYYY)", r"\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Phone Number", r"\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}"),
        ("Email Address", r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"),
        ("Policy / Document Number", r"POL[-\s]?\d{4,}"),
        ("Classification Marking", r"CONFIDENTIAL|RESTRICTED|INTERNAL|PROPRIETARY"),
        ("Effective / Expiration Date", r"[Ee](?:ffective|xpir\w*)\s*:?\s*\d{1,2}/\d{1,2}/\d{2,4}"),
        ("Retention Code", r"RET[-\s]?\d{3,}"),
        ("Account Number", r"[Aa]cct?\.?\s*#?\s*\d{4,}"),
    ],
}

WIZARD_CATEGORY_ORDER = [
    "Common / General",
    "Business / Finance",
    "Legal",
    "Medical / Healthcare",
    "Engineering / Technical",
    "Real Estate",
    "HR / Admin",
    "Compliance / Audit",
]
